Insurance/Models/Policy.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.ComponentModel.DataAnnotations;

namespace Insurance.Models
{
    public class Policy
    {
        [Key] // autoincrement id for policy
        public int Id { get; set; }

        [Required] // policynumber is a unique 5 character string(made of numbers)
        [StringLength(5)]
        public string PolicyNumber { get; set; }

        [Display(Name = "Тип")]
        public string PolicyType { get; set; } // the type of policy

        public int OwnerId { get; set; } // insured user id

        [Display(Name = "Осигуреник")]
        public User Owner { get; set; } // info about insured

        public int AgentId { get; set; } // agent for the policy

        [Display(Name = "Агент")]
        public Agent Agent { get; set; } // info about the agent

        [Display(Name = "Каско полиса")]
        public CascoPolicy CP { get; set; }

        [Display(Name = "Патничко")]
        public TravelPolicy TP { get; set; }

        [Display(Name = "Здравствено")]
        public HealthPolicy HP { get; set; }

    }
}

Insurance/Models/PolicyType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Insurance.Models
{
    public class PolicyType
    {
        public const string CascoPolicy = "CascoPolicy";
        public const string HealthPolicy = "HealthPolicy";
        public const string TravelPolicy = "TravelPolicy";
    }
}

Insurance/Controllers/PoliciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Insurance.Data;
using Insurance.Models;
using Insurance.ViewModels;

namespace Insurance.Controllers
{
    public class PoliciesController : Controller
    {
        private readonly InsuranceContext _context;

        public PoliciesController(InsuranceContext context)
        {
            _context = context;
        }

        // GET: Policies
        public async Task<IActionResult> Index(string searchString, string pt)
        {
            IQueryable<Policy> policies = _context.Policy.AsQueryable();
            IQueryable<string> policyTypes = _context.Policy.OrderBy(m => m.PolicyType).Select(m => m.PolicyType).Distinct();

            if(!string.IsNullOrEmpty(searchString))
            {
                policies = policies.Where(s => s.PolicyNumber.Contains(searchString));
            }

            if(!string.IsNullOrEmpty(pt))
            {
                policies = policies.Where(x => x.PolicyType == pt);
            }

            policies = policies.Include(m => m.Owner).Include(m => m.Agent);

            var groupPoliciesVM = new GroupPoliciesViewModel
            {
                PolicyType = new SelectList(await policyTypes.ToListAsync()),
                Policies = await policies.ToListAsync()
            };

            //var insuranceContext = _context.Policy.Include(p => p.Agent).Include(p => p.Owner);
            return View(groupPoliciesVM);
        }

        // GET: Policies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policy
                .Include(p => p.Agent)
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (policy == null)
            {
                return NotFound();
            }

            return View(policy);
        }

        // GET: Policies/Create
        public IActionResult Create()
        {
            ViewData["AgentId"] = new SelectList(_context.Agent, "Id", "AgentNumber");
            ViewData["OwnerId"] = new SelectList(_context.User, "Id", "EMBG");
            return View();
        }

        // POST: Policies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PolicyNumber,PolicyType,OwnerId,AgentId")] Policy policy)
        {
            if (ModelState.IsValid)
            {
                _context.Add(policy);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AgentId"] = new SelectList(_context.Agent, "Id", "AgentNumber", policy.AgentId);
            ViewData["OwnerId"] = new SelectList(_context.User, "Id", "EMBG", policy.OwnerId);
            return View(policy);
        }

        // GET: Policies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policy.FindAsync(id);
            if (policy == null)
            {
                return NotFound();
            }
            ViewData["AgentId"] = new SelectList(_context.Agent, "Id", "AgentNumber", policy.AgentId);
            ViewData["OwnerId"] = new SelectList(_context.User, "Id", "EMBG", policy.OwnerId);
            return View(policy);
        }

        // POST: Policies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PolicyNumber,PolicyType,OwnerId,AgentId")] Policy policy)
        {
            if (id != policy.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(policy);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PolicyExists(policy.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AgentId"] = new SelectList(_context.Agent, "Id", "AgentNumber", policy.AgentId);
            ViewData["OwnerId"] = new SelectList(_context.User, "Id", "EMBG", policy.OwnerId);
            return View(policy);
        }

        // GET: Policies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var policy = await _context.Policy
                .Include(p => p.Agent)
                .Include(p => p.Owner)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (policy == null)
            {
                return NotFound();
            }

            return View(policy);
        }

        // POST: Policies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var policy = await _context.Policy.FindAsync(id);
            _context.Policy.Remove(policy);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PolicyExists(int id)
        {
            return _context.Policy.Any(e => e.Id == id);
        }
    }
}

Insurance/Views/Policies/Create.cshtml
@model Insurance.Models.Policy

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Policy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PolicyNumber" class="control-label"></label>
                <input asp-for="PolicyNumber" class="form-control" />
                <span asp-validation-for="PolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PolicyType" class="control-label"></label>
                <input asp-for="PolicyType" class="form-control" />
                <span asp-validation-for="PolicyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class ="form-control" asp-items="ViewBag.OwnerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AgentId" class="control-label"></label>
                <select asp-for="AgentId" class ="form-control" asp-items="ViewBag.AgentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Insurance/Views/Policies/Delete.cshtml
@model Insurance.Models.Policy

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Policy</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.EMBG)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agent.AgentNumber)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Insurance/Views/Policies/Details.cshtml
@model Insurance.Models.Policy

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Policy</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PolicyType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PolicyType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Owner)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Owner.EMBG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agent)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agent.AgentNumber)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Insurance/Views/Policies/Edit.cshtml
@model Insurance.Models.Policy

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Policy</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="PolicyNumber" class="control-label"></label>
                <input asp-for="PolicyNumber" class="form-control" />
                <span asp-validation-for="PolicyNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PolicyType" class="control-label"></label>
                <input asp-for="PolicyType" class="form-control" />
                <span asp-validation-for="PolicyType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OwnerId" class="control-label"></label>
                <select asp-for="OwnerId" class="form-control" asp-items="ViewBag.OwnerId"></select>
                <span asp-validation-for="OwnerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AgentId" class="control-label"></label>
                <select asp-for="AgentId" class="form-control" asp-items="ViewBag.AgentId"></select>
                <span asp-validation-for="AgentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Insurance/Views/Policies/Index.cshtml
@model Insurance.ViewModels.GroupPoliciesViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>My Policies</h1>

<form asp-controller="Policies" asp-action="Index" method="get">
    <p>
        <select asp-for="PT" asp-items="Model.PolicyType">
            <option value="">ALL</option>
        </select>
        Title: <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Policies[0].PolicyNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Policies[0].PolicyType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Policies[0].Owner.EMBG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Policies[0].Agent.AgentNumber)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Policies) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PolicyType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Owner.EMBG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Agent.AgentNumber)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>